branch-defaults:
  master:
    environment: todo-backend-production
deploy:
  artifact: target/service-0.0.1-SNAPSHOT.jar
global:
  application_name: todo-backend
  branch: null
  default_ec2_keyname: my-pair-key
  default_platform: Java 8
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
